name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: mamae123
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
        options: --health cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Configure MySQL permissions
      run: mysql -h 127.0.0.1 --port3306 -u root -pmamae123 -e "ALTER USER 'root'@'%' IDENTIFIED BY 'mamae123'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Install client mysql
      run: sudo apt install mysql-client
    - name: Criar Tabelas
      run: mysql -h 127.0.0.1 --port 3306 -u user1 -p mamae123 usersdb < estrutura.sql
    - name: Run tests
      env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: mamae123
          MYSQL_DATABASE: usersdb
      run: npm test